# Generated by Django 3.0.5 on 2020-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='nbr',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productorder',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
